name: Linting, Testing, Building
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod
        if: always()

      - name: linting typescript
        run: npm run lint:ts
        if: always()

      - name: linting css
        run: npm run lint:scss
        if: always()

      - name: unit testing
        run: npm run test:unit
        if: always()

      - name: build storybook
        run: npm run storybook:build
        if: always()

      - name: ui testing
        run: npm run test:ui:ci
        if: always()
